spring.application.name=SpringStarter
spring.datasource.url=jdbc:mysql://localhost:3306/mockitoTraining
spring.datasource.username=root
spring.datasource.password=sa@02@272820
spring.jpa.generate-ddl = true